apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"labels":{"type":"web"},"name":"mypod","namespace":"default"},"spec":{"containers":[{"image":"nginx:latest","name":"mypod"}],"restartPolicy":"Always"},"status":{}}
  creationTimestamp: "2024-12-15T19:31:46Z"
  labels:
    type: web
  name: mypod
  namespace: default
  resourceVersion: "46436"
  uid: 7707ffda-12c3-4fb2-b914-0616bfb3e85d
spec:
  containers:
  - image: abramdocker/customwebapp:7
    imagePullPolicy: Always
    name: mypod
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bdkvk
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: k8-dev-worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-bdkvk
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T19:31:46Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T19:31:54Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T19:31:54Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-12-15T19:31:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://e4ce2dbc49e0b817dd2f3dbc19d1f3e8e0b76beda3f3e02f1ff3adc2cc488508
    image: docker.io/abramdocker/customwebapp:7
    imageID: docker.io/abramdocker/customwebapp@sha256:9859f457473083fb179bb342b97d47726deb08efd48e2dd993dbe9c76c4c3391
    lastState:
      terminated:
        containerID: containerd://170e2e2262a49d67496b1596e894d032fb5cf195f46a7fc4d1c98260da260f62
        exitCode: 0
        finishedAt: "2024-12-15T19:39:56Z"
        reason: Completed
        startedAt: "2024-12-15T19:31:53Z"
    name: mypod
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2024-12-15T19:40:23Z"
  hostIP: 172.18.0.4
  phase: Running
  podIP: 10.244.2.6
  podIPs:
  - ip: 10.244.2.6
  qosClass: BestEffort
  startTime: "2024-12-15T19:31:46Z"
